name: master commit test

on:
    push:
        branches:
            master

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            
            - name: php setup
              uses: nanasess/setup-php@master
              with:
                php-version: ['7.2', '7.3', '7.4']

            - run: composer install --dev

            - run: vendor/bin/phpunit

            - run: vendor/bin/php-coveralls -v -c .coveralls.yml

