name: master commit test

on:
    push:
        branches:
            master

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-versions: ['7.3', '7.4']

        steps:
            - uses: actions/checkout@v1
            
            - name: php setup
              uses: shivammathur/setup-php@master
              with:
                php-version: ${{ matrix.php-versions }}
                coverage: xdebug

            - name: output php version infomation
              run: php -v
        
            - run: composer install

            - name: install phpstan
              run: composer require phpstan/phpstan

            - run: vendor/bin/phpunit

            - run: vendor/bin/phpstan analyze src/ -l max

            - run: vendor/bin/php-coveralls -v -c .coveralls.yml

